#pragma once

#include "Animation.h"
#include "Animations.h"
#include "AnimationFrame.h"
#include "debug.h"
#include "Game.h"
#include "GameObject.h"
#include "KeyEventHandler.h"
#include "MovableObject.h"
#include "Sprite.h"
#include "Sprites.h"
#include "Textures.h"

#include "Board.h"
#include "Simon.h"
#include "Rope.h"
#include "BigCandle.h"
#include "Flame.h"
#include "Flames.h"
#include "ItemRope.h"
#include "InvisibleWall.h"
#include "Items.h"
#include "BigHeart.h"
#include "Heart.h"
#include "ItemDagger.h"
#include "Candle.h"
#include "StairsUp.h"
#include "StairsDown.h"
#include "Panther.h"
#include "Zombie.h"
#include "SpawnerZombie.h"
#include "SpawnerPanther.h"
#include "SpawnerPinkBat.h"
#include "PinkBat.h"
#include "Camera.h"
#include "Portal.h"
#include "Portals.h"
#include "Fish.h"
#include "FireBall.h"	
#include "SpawnerFish.h"
#include "Bubble.h"
#include "Bubbles.h"
#include "InvisibleWater.h"
#include "BossBat.h"
#include "SecretBrick.h"
#include "Rock.h"
#include "Rocks.h"
#include "ItemMeat.h"
#include "AutoMoveZone.h"
#include "Gate.h"
#include "MoneyBag.h"
#include "Cross.h"
#include "ItemAxe.h"
#include "ItemHolyWater.h"
#include "Axe.h"
#include "HolyWater.h"
#include "CameraEvent.h"
#include "ItemSuperPotion.h"
#include "Watch.h"
#include "DoubleShot.h"
#include "MagicBall.h"

#define ID_TEX_SIMON		0
#define ID_TEX_ROPE			1
#define ID_TEX_GROUND		2
#define ID_TEX_MISC			3
#define ID_TEX_MONSTERS		4
#define ID_TEX_TILESET		5

